const DECISIONS_URL = "https://api.typesafe.ai/v1/systemone";
const MODEL = "jev-latest";

export const WHICH_AI_LABELS = ["human", "claude", "gpt", "gemini", "grok", "copilot", "other"] as const;
export type WhichAiLabel = (typeof WHICH_AI_LABELS)[number];

export interface JevResult {
  isAiNoul: number;
  whichAi: WhichAiLabel;
  probabilities: Record<string, number>;
  inputTokens: number;
  outputTokens: number;
  elapsedMs: number;
}

function isWhichAiLabel(v: unknown): v is WhichAiLabel {
  return typeof v === "string" && (WHICH_AI_LABELS as readonly string[]).includes(v);
}

export const EXCLUSION_NOTE =
  "Judge only the author's own prose. Ignore quoted text (lines beginning with \">\") and any fenced or inline code blocks. Quotes and code are often copied from elsewhere and say nothing about who wrote the surrounding message.";

export const STRUCTURE_NOTE = `AI-written text is often long, exhaustive, and over-structured: many headed sections, numbered plans, nested bullet lists, uniform formatting, and a comprehensive, polished, emotionless tone. Humans usually write shorter, messier, more informal messages, with typos, incomplete thoughts, slang, blunt opinions, and personal voice. Weigh the structure and completeness of the whole document, not only its prose.

Common tells of AI writing: filler like "it's worth noting" and "at the end of the day"; inflated words such as delve, leverage, utilise, robust, seamless, underscore; binary contrasts like "it's not X, it's Y"; and sycophantic openers like "Great question" or "I hope this helps".`;

export const GITHUB_CONTEXT =
  "You are judging the text of a GitHub issue, pull request, or code-review comment, to decide who wrote it.";

export const IS_AI_INSTRUCTIONS = `${GITHUB_CONTEXT} Was this text generated by a large language model or AI assistant, in whole or in substantial part? 1 means definitely AI-generated, 0 means definitely written by a human. ${STRUCTURE_NOTE} ${EXCLUSION_NOTE}`;

export const WHICH_AI_INSTRUCTIONS = `${GITHUB_CONTEXT} Which AI most likely wrote this text? If it reads as AI-generated, prefer the specific model (including GitHub Copilot) over "human"; only pick "human" when the writing genuinely reads as human. ${STRUCTURE_NOTE} ${EXCLUSION_NOTE}`;

export const WHICH_AI_CRITERIA: Record<WhichAiLabel, string> = {
  human: "A human wrote this text.",
  claude: "Anthropic's Claude wrote this text.",
  gpt: "OpenAI's GPT wrote this text.",
  gemini: "Google's Gemini wrote this text.",
  grok: "xAI's Grok wrote this text.",
  copilot: "GitHub Copilot wrote this text.",
  other: "Some other AI wrote this text.",
};

export function parseDecisionsResponse(data: unknown): Omit<JevResult, "elapsedMs"> {
  const answers = (data as { answers?: unknown })?.answers as
    | { is_ai?: { noul?: unknown }; which_ai?: { choice?: unknown; probabilities?: unknown } }
    | undefined;

  const noul = answers?.is_ai?.noul;
  const choice = answers?.which_ai?.choice;
  const probabilities = answers?.which_ai?.probabilities;

  if (typeof noul !== "number" || !isWhichAiLabel(choice) || typeof probabilities !== "object" || probabilities === null) {
    throw new Error(`Jev response shape unexpected: ${JSON.stringify(data).slice(0, 500)}`);
  }

  const usage = (data as { usage?: { input_tokens?: unknown; output_tokens?: unknown } }).usage;
  const inputTokens = typeof usage?.input_tokens === "number" ? usage.input_tokens : 0;
  const outputTokens = typeof usage?.output_tokens === "number" ? usage.output_tokens : 0;

  return {
    isAiNoul: noul,
    whichAi: choice,
    probabilities: probabilities as Record<string, number>,
    inputTokens,
    outputTokens,
  };
}

export async function analyzeText(text: string, apiKey: string): Promise<JevResult> {
  const start = Date.now();
  const body = {
    model: MODEL,
    state: text,
    questions: {
      is_ai: {
        type: "noul",
        instructions: IS_AI_INSTRUCTIONS,
      },
      which_ai: {
        type: "choice",
        instructions: WHICH_AI_INSTRUCTIONS,
        criteria: WHICH_AI_CRITERIA,
      },
    },
  };

  const res = await fetch(DECISIONS_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`Jev decisions API returned ${res.status}: ${detail}`);
  }

  const parsed = parseDecisionsResponse(await res.json());
  return { ...parsed, elapsedMs: Date.now() - start };
}
